# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#  "identity" : "1234567890",
 "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###



# Login
POST http://localhost:8899/api/auth/me HTTP/1.1
Content-Type: application/json

{
  "identity" : "andy@ggg.mail",
  "password" : "123456"
}

###

# Post message
POST http://localhost:8899/api/post

###

#test not-found
GET http://localhost:8899/api/product

###

GET http://localhost:8899/api/auth/me

###

