# Get Me
GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzczMzcyMjQzLCJleHAiOjE3NzQ2NjgyNDN9.cY0kWJpltdX_Av1WzAgokX3CIa4uJZPt8ei6zdAZkpI
###

# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "andy@ggg.mail",
 "password" : "123456"
}
###



# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#  "identity" : "12345678",
 "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###



# Post message
POST http://localhost:8899/api/post

###

#test not-found
GET http://localhost:8899/api/product

###

GET http://localhost:8899/api/auth/me

###

